### ISSUE TITLE
CoffeeManga chapters don’t load

### ISSUE THREAD

**Issue by JRDSandstorm** [TheNetsky/extensions-generic-0.8#48] opened 2023-09-02 11:17 UTC
**Describe the bug**
All CoffeeManga chapters return Paperback: JSError Error [PaperbackError(300)] JSError Error: Could not parse page for postID:#### chapterID:chapter-## - @ asyncFunctionResume@[native code] @[native code] promiseReactionJobWithoutPromise@[native code] promiseReactionJobWithoutPromise@[native code]:9015:32

**To Reproduce**
Open any CoffeeManga chapter, doesn’t need to be added to library.

**Expected behavior**
Should open and load chapter but it doesn’t.

**Screenshots/Video**

**App version**
- v0.8.6-r2

**Source WITH source version**
Madara Generic (0.8) - CoffeeManga 3.1.1

**Additional context**
Tried purging and reinstalling source but issue still remains.

**Comment by TheNetsky** [comment] 2023-09-02 11:19
Post on correct repo next time.

**Comment by Ivanmatthew** [comment] 2023-10-12 08:08
> **Describe the bug** All CoffeeManga chapters return Paperback: JSError Error [PaperbackError(300)] JSError Error: Could not parse page for postID:#### chapterID:chapter-## - @ asyncFunctionResume@[native code] @[native code] promiseReactionJobWithoutPromise@[native code] promiseReactionJobWithoutPromise@[native code]:9015:32
> 
> **To Reproduce** Open any CoffeeManga chapter, doesn’t need to be added to library.
> 
> **Expected behavior** Should open and load chapter but it doesn’t.
> 
> **Screenshots/Video** If applicable, add screenshots to help explain your problem.
> 
> **App version**
> 
> * v0.8.6-r2
> 
> **Source WITH source version** Madara Generic (0.8) - CoffeeManga 3.1.1
> 
> **Additional context** Tried purging and reinstalling source but issue still remains.

This is fixed with PR #64 .
The reason why this didn’t work before is due to CoffeeManga always adding the “data-src” attribute to anything but their first image. The problem is, is that they don’t use it and is just left empty. However since it is added in the element, it is a valid attribute and therefore will not be marked as undefined.
The parser only checked if the attribute found was undefined or not, which meant that if you apply the logic to an empty “data-src” attribute, it would match and say the image url is an empty string.
It also does not correct itself, because the conditional flow is written in an if-elseif-else way, meaning that it will match the first found attribute and skip the rest (E.g. check data-src first, then src, then data-cfsrc etc.)

**Comment by TheNetsky** [comment] 2023-10-12 13:28
Indeed fixed in #64, thanks for the help!

**Closed as completed by TheNetsky** 2023-10-12 13:28 UTC
Labels: bug, madara
